/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Policies */
        get: operations["list_policies_api_v1_policies_get"];
        put?: never;
        /** Create Policy */
        post: operations["create_policy_api_v1_policies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/{policy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Policy */
        get: operations["get_policy_api_v1_policies__policy_id__get"];
        put?: never;
        post?: never;
        /** Delete Policy */
        delete: operations["delete_policy_api_v1_policies__policy_id__delete"];
        options?: never;
        head?: never;
        /** Update Policy */
        patch: operations["update_policy_api_v1_policies__policy_id__patch"];
        trace?: never;
    };
    "/api/v1/policies/{policy_id}/dry-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dry Run Policy
         * @description Evaluate `text` against the live policy rules with this rule's current
         *     field values overlaid — regardless of whether the row is enabled — so
         *     you can preview a rule you're about to save. Writes no audit record.
         */
        post: operations["dry_run_policy_api_v1_policies__policy_id__dry_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit */
        get: operations["list_audit_api_v1_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audit Record */
        get: operations["get_audit_record_api_v1_audit__record_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats Summary */
        get: operations["stats_summary_api_v1_stats_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats Timeseries */
        get: operations["stats_timeseries_api_v1_stats_timeseries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health check endpoint.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan
         * @description Run the three-pass detection pipeline on a string — no LLM involved.
         *
         *     Returns the policy decision (ALLOW / MASK / BLOCK), every finding (entity
         *     type, matched text, confidence, which detector caught it), the redacted
         *     version of the text, and detection latency. This is what the public demo
         *     calls; it needs no LLM backend or database.
         */
        post: operations["scan_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Completions
         * @description OpenAI-compatible chat completions endpoint with PII/secret scanning.
         *
         *     Full pipeline: scan → policy → redact → audit → forward/block → output scan → return.
         */
        post: operations["chat_completions_v1_chat_completions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuditDetail
         * @description Full record for the audit detail drawer — adds what the list view omits.
         */
        AuditDetail: {
            /** Id */
            id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            decision: components["schemas"]["Decision"];
            /** Matched Rule Ids */
            matched_rule_ids: string[];
            /** Latency Ms */
            latency_ms: number;
            /** Detector Confidence */
            detector_confidence?: number | null;
            /** Entity Types */
            entity_types: string[];
            /** Request Preview */
            request_preview: string;
            /** Tenant Id */
            tenant_id?: string | null;
            /** Model */
            model: string;
            input_decision: components["schemas"]["Decision"];
            output_decision?: components["schemas"]["Decision"] | null;
            /** Reasons */
            reasons: string[];
            /** Input Redactions */
            input_redactions: {
                [key: string]: number;
            };
            /** Output Redactions */
            output_redactions: {
                [key: string]: number;
            };
            /** Prompt Redacted */
            prompt_redacted: string;
            /** Response Redacted */
            response_redacted?: string | null;
            /** Detection Latency Ms */
            detection_latency_ms: number;
            /** Llm Latency Ms */
            llm_latency_ms?: number | null;
            /** Total Latency Ms */
            total_latency_ms: number;
            /** Policy Id */
            policy_id: string;
        };
        /**
         * AuditRecord
         * @description A single audit log entry, as surfaced to the console.
         *
         *     Field mapping from the `audit_log` table (see app/db.py `AuditLog`):
         *       - decision            <- input_decision if BLOCK, else the worse of
         *                                 (input_decision, output_decision) by
         *                                 ALLOW < MASK < BLOCK. The effective outcome
         *                                 a developer cares about, not a raw column.
         *       - matched_rule_ids     <- keys of input_redactions ∪ output_redactions.
         *                                 The audit table doesn't store rule IDs (only
         *                                 human-readable `reasons` strings), so this is
         *                                 the entity types that fired, which is the
         *                                 closest real signal — not a fabricated ID.
         *       - entity_types          <- same source as matched_rule_ids.
         *       - detector_confidence   <- always None. Per-finding confidence isn't
         *                                 persisted in the audit table (only redaction
         *                                 *counts* by entity type are). Not faked.
         *       - tenant_id             <- user_id column, renamed to match the plan's
         *                                 multi-tenant-shaped field. This project has
         *                                 no real tenant concept yet.
         *       - request_preview       <- prompt_redacted, truncated to 200 chars.
         *                                 Already redacted before it reached the DB.
         */
        AuditRecord: {
            /** Id */
            id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            decision: components["schemas"]["Decision"];
            /** Matched Rule Ids */
            matched_rule_ids: string[];
            /** Latency Ms */
            latency_ms: number;
            /** Detector Confidence */
            detector_confidence?: number | null;
            /** Entity Types */
            entity_types: string[];
            /** Request Preview */
            request_preview: string;
            /** Tenant Id */
            tenant_id?: string | null;
        };
        /**
         * ChatCompletionRequest
         * @description OpenAI-compatible chat completion request.
         *
         *     Accepts all standard fields. Unknown fields are passed through
         *     to the LLM backend.
         */
        ChatCompletionRequest: {
            /** Model */
            model: string;
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
            /** Temperature */
            temperature?: number | null;
            /** Top P */
            top_p?: number | null;
            /** N */
            n?: number | null;
            /**
             * Stream
             * @default false
             */
            stream: boolean | null;
            /** Stop */
            stop?: string | string[] | null;
            /** Max Tokens */
            max_tokens?: number | null;
            /** Presence Penalty */
            presence_penalty?: number | null;
            /** Frequency Penalty */
            frequency_penalty?: number | null;
            /** User */
            user?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ChatMessage
         * @description A single message in the chat conversation.
         */
        ChatMessage: {
            /** Role */
            role: string;
            /** Content */
            content?: string | null;
            /** Name */
            name?: string | null;
            /** Tool Calls */
            tool_calls?: unknown[] | null;
            /** Tool Call Id */
            tool_call_id?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * Decision
         * @enum {string}
         */
        Decision: "allow" | "mask" | "block";
        /** DryRunFinding */
        DryRunFinding: {
            entity_type: components["schemas"]["EntityType"];
            category: components["schemas"]["EntityCategory"];
            /** Text */
            text: string;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Confidence */
            confidence: number;
            /** Detector */
            detector: string;
        };
        /** DryRunRequest */
        DryRunRequest: {
            /** Text */
            text: string;
        };
        /** DryRunResponse */
        DryRunResponse: {
            decision: components["schemas"]["Decision"];
            /** Reasons */
            reasons: string[];
            /** Findings */
            findings: components["schemas"]["DryRunFinding"][];
            /** Redacted Text */
            redacted_text: string;
            /** Latency Ms */
            latency_ms: number;
        };
        /**
         * EntityCategory
         * @description High-level category of a detected entity.
         * @enum {string}
         */
        EntityCategory: "PII" | "SECRET";
        /**
         * EntityType
         * @description Types of sensitive entities that SentinelLM can detect.
         * @enum {string}
         */
        EntityType: "EMAIL" | "PHONE" | "SSN" | "CREDIT_CARD" | "AWS_KEY" | "GITHUB_TOKEN" | "JWT" | "PASSWORD" | "PERSON_NAME" | "GENERIC_PII" | "GENERIC_SECRET";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PaginatedAudit */
        PaginatedAudit: {
            /** Items */
            items: components["schemas"]["AuditRecord"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** PaginatedPolicies */
        PaginatedPolicies: {
            /** Items */
            items: components["schemas"]["PolicyRule"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** PolicyCreate */
        PolicyCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            entity_type: components["schemas"]["EntityType"];
            action: components["schemas"]["Decision"];
            /**
             * Min Confidence
             * @default 0.5
             */
            min_confidence: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /**
         * PolicyRule
         * @description A single policy rule, as stored in the `policies` table.
         */
        PolicyRule: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            entity_type: components["schemas"]["EntityType"];
            category: components["schemas"]["EntityCategory"];
            action: components["schemas"]["Decision"];
            /** Min Confidence */
            min_confidence: number;
            /** Enabled */
            enabled: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PolicyUpdate
         * @description All fields optional — PATCH semantics. Only provided fields change.
         */
        PolicyUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            entity_type?: components["schemas"]["EntityType"] | null;
            action?: components["schemas"]["Decision"] | null;
            /** Min Confidence */
            min_confidence?: number | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /**
         * ScanRequest
         * @description Request body for the detect-only /scan endpoint.
         */
        ScanRequest: {
            /** Text */
            text: string;
        };
        /** StatsSummary */
        StatsSummary: {
            /** Window */
            window: string;
            /** Total */
            total: number;
            /** By Decision */
            by_decision: {
                [key: string]: number;
            };
            /** P50 Ms */
            p50_ms: number;
            /** P95 Ms */
            p95_ms: number;
            /** P99 Ms */
            p99_ms: number;
            /**
             * Top Rules
             * @description Top entity types by trigger count in the window — the closest real proxy to 'top rules' (see AuditRecord.matched_rule_ids).
             */
            top_rules: [
                string,
                number
            ][];
        };
        /** TimeseriesPoint */
        TimeseriesPoint: {
            /**
             * Bucket
             * Format: date-time
             */
            bucket: string;
            /** Allow */
            allow: number;
            /** Mask */
            mask: number;
            /** Block */
            block: number;
            /** P95 Ms */
            p95_ms: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_policies_api_v1_policies_get: {
        parameters: {
            query?: {
                enabled?: boolean | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPolicies"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_policy_api_v1_policies_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyRule"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_policy_api_v1_policies__policy_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyRule"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_policy_api_v1_policies__policy_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_policy_api_v1_policies__policy_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyRule"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dry_run_policy_api_v1_policies__policy_id__dry_run_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DryRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DryRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_api_v1_audit_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                decision?: components["schemas"]["Decision"] | null;
                /** @description Entity type that fired (e.g. AWS_KEY) — see AuditRecord.matched_rule_ids. */
                rule_id?: string | null;
                /** @description Free-text search over redacted content */
                q?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAudit"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_record_api_v1_audit__record_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_summary_api_v1_stats_summary_get: {
        parameters: {
            query?: {
                window?: string;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_timeseries_api_v1_stats_timeseries_get: {
        parameters: {
            query?: {
                window?: string;
                bucket?: string;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeseriesPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    scan_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_completions_v1_chat_completions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatCompletionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
